services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-scm}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-userpassword}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  app:
    build:
      context: .  # Path to Dockerfile (the current directory)
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST:-postgres}:5432/${DB_NAME:-scm}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-user}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-userpassword}
    ports:
      - "8080:8080"
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
